apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: create-default-disk-labeled-nodes
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: longhorn
    storage.e-dani.com/change: sauvage-attach-only
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: system-managed-components-node-selector
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: longhorn
    storage.e-dani.com/change: sauvage-attach-only
value: "storage-longhorn:true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: taint-toleration
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: longhorn
    storage.e-dani.com/change: sauvage-attach-only
value: "dedicated=llm:NoSchedule;role=edge:NoSchedule;pocharlies.io/pool=bulk:NoSchedule"
