apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - app.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: sauvage-bot
      app.kubernetes.io/part-of: sauvage-moderation
      app.kubernetes.io/managed-by: argocd
