apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sauvage-bot-runtime
  namespace: sauvage-bot
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: sauvage-bot-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_USER
      remoteRef:
        key: sauvage-bot/DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: sauvage-bot/DB_PASSWORD
    - secretKey: OPENAI_TOKEN
      remoteRef:
        key: sauvage-bot/OPENAI_TOKEN
    - secretKey: TELEGRAM_TOKEN
      remoteRef:
        key: sauvage-bot/TELEGRAM_TOKEN
    - secretKey: SERVER_AUTH_HASH
      remoteRef:
        key: sauvage-bot/SERVER_AUTH_HASH
    - secretKey: SAUVAGE_INTERNAL_TOKEN
      remoteRef:
        key: sauvage-bot/SAUVAGE_INTERNAL_TOKEN
