apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sauvage-bot-runtime
  namespace: sauvage-bot
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sauvage-bot-runtime
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_USER
      remoteRef:
        key: sauvage-bot
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: sauvage-bot
        property: DB_PASSWORD
    - secretKey: OPENAI_TOKEN
      remoteRef:
        key: sauvage-bot
        property: OPENAI_TOKEN
    - secretKey: TELEGRAM_TOKEN
      remoteRef:
        key: sauvage-bot
        property: TELEGRAM_TOKEN
    - secretKey: SERVER_AUTH_HASH
      remoteRef:
        key: sauvage-bot
        property: SERVER_AUTH_HASH
    - secretKey: SAUVAGE_INTERNAL_TOKEN
      remoteRef:
        key: sauvage-bot
        property: SAUVAGE_INTERNAL_TOKEN
