apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-app
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/component: database
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: keycloak-postgres-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-next-postgres/username
    - secretKey: password
      remoteRef:
        key: keycloak-next-postgres/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-minio
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/component: backup-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: keycloak-postgres-minio
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: postgres-shared-minio/access_key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: postgres-shared-minio/secret_access_key
