apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-app
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-postgres-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: secret/keycloak-next/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secret/keycloak-next/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-minio
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/component: backup-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-postgres-minio
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: postgres-shared/minio
        property: access_key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: postgres-shared/minio
        property: secret_access_key
