---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-node-agent-config
  namespace: velero
data:
  node-agent-config.json: |
    {
      "loadConcurrency": {
        "globalConfig": 1,
        "prepareQueueLength": 6
      },
      "podResources": {
        "cpuRequest": "10m",
        "cpuLimit": "1000m",
        "memoryRequest": "128Mi",
        "memoryLimit": "1Gi"
      }
    }
