#!/bin/sh
set -eu

umask 077

# Dedicated confidential client for the Alexa skill jarvis-alexa (ns jarvis,
# pocharlies-org/jarvis alexa-skill/echo.py): it reads the Echo Show's Agenda
# calendar with calendar_list_events through AgentGateway /workspace. Its
# service account holds exactly ONE realm role, the shared route role
# agentgateway-read:workspace, and NOTHING from the agentgateway-write family.
#
# INFRA-477: the client was created by hand through the admin API on 2026-10-03
# by the INFRA-411 session (the process error this reconciler closes) and
# approved by security in k8s-agentgateway-pocharlies#170 (identity-bindings
# for sub 1bcb6c47-0a01-4717-959d-9755e2c9ad36). This hook ADOPTS it: the
# service account and its stable sub survive reconcile, so the identity
# bindings keep matching. The role itself is CREATED elsewhere
# (agentgateway-read-grants.sh, sync-wave 20) and only VERIFIED here; the
# holder allowlist of that shared role is also owned by that hook (INFRA-477
# widened it with service-account-jarvis-echo), which runs before this one.
#
# The client SECRET is deliberately not managed here: it was generated by
# Keycloak on 2026-10-03, is not in 1Password yet (quota), and will be carried
# into a Secret by an ExternalSecret in k8s-jarvis — never by this Job. The
# token-mint verification reads the current secret through the admin API
# (GET, the same idiom as agentgateway-read-grants.sh) and never prints it.
#
# fullScopeAllowed=false is the owned steady state (INFRA-45 pattern). The
# live client was adopted with the flag true (measured 2026-10-04), so the
# update path of the upsert deliberately does NOT touch the flag: the flip is
# performed by ensure_fullscope_off AFTER the role is mapped into the client
# role scope, with a pre-flip mint proving the grant travels and an
# auto-restore (read-back + confirmation mint) if the post-flip token is
# off-matrix — the Alexa skill never loses its token to a failed reconcile.
# With the flag off the minted token carries exactly the reviewed role (the
# measured behavior on openclaw-readonly-agentgateway, INFRA-44).

MODE="${MODE:-ensure}"
KEYCLOAK_URL="${KEYCLOAK_URL:-http://keycloak.keycloak.svc.cluster.local}"
REALM="${REALM:-edani}"
CLIENT_ID="${CLIENT_ID:-jarvis-echo}"
READ_ROLE_NAME="${READ_ROLE_NAME:-agentgateway-read:workspace}"
EXPECTED_READ_ROLE_NAME="agentgateway-read:workspace"
AGENTGATEWAY_AUDIENCE="${AGENTGATEWAY_AUDIENCE:-mcp.lan.e-dani.com}"
MAPPER_NAME="${MAPPER_NAME:-aud-mcp}"
KCADM="${KCADM:-/opt/keycloak/bin/kcadm.sh}"
ADMIN_CONFIG=/tmp/kcadm-jarvis-echo-admin.config
CLIENT_CONFIG=/tmp/kcadm-jarvis-echo-client.config

cleanup() {
  rm -f "${ADMIN_CONFIG}" "${CLIENT_CONFIG}"
}
trap cleanup EXIT HUP INT TERM

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

progress() {
  printf '{"client_id":"%s","stage":"%s"}\n' "${CLIENT_ID}" "$1"
}

[ "${CLIENT_ID}" = "jarvis-echo" ] || fail "unsupported immutable client"
[ "${READ_ROLE_NAME}" = "${EXPECTED_READ_ROLE_NAME}" ] || \
  fail "READ_ROLE_NAME is immutable; review this reconciler, the read-grants holder allowlist and the gateway CEL together"
[ "${MAPPER_NAME}" = "aud-mcp" ] || fail "MAPPER_NAME is immutable"
case "${MODE}" in
  ensure|audit|rollback) ;;
  *) fail "MODE must be ensure, audit or rollback" ;;
esac

nonempty_lines() { sed '/^[[:space:]]*$/d'; }

line_count() { nonempty_lines | wc -l | tr -d '[:space:]'; }

login_admin() {
  attempt=1
  while [ "${attempt}" -le 30 ]; do
    if "${KCADM}" config credentials \
      --config "${ADMIN_CONFIG}" \
      --server "${KEYCLOAK_URL}" \
      --realm master \
      --user "${KC_BOOTSTRAP_ADMIN_USERNAME}" \
      --password "${KC_BOOTSTRAP_ADMIN_PASSWORD}" >/dev/null 2>&1; then
      return 0
    fi
    attempt=$((attempt + 1))
    sleep 5
  done
  fail "Keycloak admin login did not become ready"
}

kget() {
  "${KCADM}" get "$@" --config "${ADMIN_CONFIG}" -r "${REALM}"
}

resolve_client_optional() {
  rows="$(kget clients -q "clientId=${CLIENT_ID}" --fields id --format csv --noquotes | nonempty_lines)"
  [ "$(printf '%s\n' "${rows}" | line_count)" -le 1 ] || fail "duplicate client ${CLIENT_ID}"
  printf '%s' "${rows}"
}

require_client() {
  uuid="$(resolve_client_optional)"
  [ -n "${uuid}" ] || fail "client ${CLIENT_ID} is missing"
  printf '%s' "${uuid}"
}

client_field() {
  kget "clients/$1" --fields "$2" --format csv --noquotes | nonempty_lines
}

assert_client_boolean() {
  actual="$(client_field "$1" "$2")"
  [ "${actual}" = "$3" ] || fail "client field $2 expected $3"
}

upsert_client() {
  # Neither branch carries a secret: create lets Keycloak generate one (fresh
  # bootstrap only — the live client already exists), and update must never
  # overwrite the secret the Alexa skill authenticates with. The create path
  # sets fullScopeAllowed=false from the start (no live traffic on a fresh
  # realm); the UPDATE path deliberately omits the flag so the flip stays
  # under ensure_fullscope_off's fail-closed order (INFRA-45 precedent).
  uuid="$(resolve_client_optional)"
  if [ -n "${uuid}" ]; then
    "${KCADM}" update "clients/${uuid}" --config "${ADMIN_CONFIG}" -r "${REALM}" \
      -s "clientId=${CLIENT_ID}" \
      -s enabled=true \
      -s publicClient=false \
      -s standardFlowEnabled=false \
      -s directAccessGrantsEnabled=false \
      -s serviceAccountsEnabled=true \
      -s protocol=openid-connect >/dev/null 2>&1 || \
      fail "failed to reconcile ${CLIENT_ID}"
  else
    "${KCADM}" create clients --config "${ADMIN_CONFIG}" -r "${REALM}" \
      -s "clientId=${CLIENT_ID}" \
      -s enabled=true \
      -s publicClient=false \
      -s standardFlowEnabled=false \
      -s directAccessGrantsEnabled=false \
      -s serviceAccountsEnabled=true \
      -s fullScopeAllowed=false \
      -s protocol=openid-connect >/dev/null 2>&1 || \
      fail "failed to reconcile ${CLIENT_ID}"
  fi
  CLIENT_UUID="$(require_client)"
}

filter_mapper_id() {
  expected="$1"
  while IFS=, read -r mapper_id mapper_name; do
    if [ "${mapper_name}" = "${expected}" ]; then
      printf '%s\n' "${mapper_id}"
    fi
  done
}

mapper_uuid_optional() {
  mapper_name="$1"
  rows="$(kget "clients/${CLIENT_UUID}/protocol-mappers/models" \
    --fields id,name --format csv --noquotes | \
    filter_mapper_id "${mapper_name}" | nonempty_lines)"
  [ "$(printf '%s\n' "${rows}" | line_count)" -le 1 ] || fail "duplicate mapper ${mapper_name}"
  printf '%s' "${rows}"
}

upsert_audience_mapper() {
  mapper_uuid="$(mapper_uuid_optional "${MAPPER_NAME}")"
  endpoint="clients/${CLIENT_UUID}/protocol-mappers/models"
  action=create
  if [ -n "${mapper_uuid}" ]; then
    endpoint="${endpoint}/${mapper_uuid}"
    action=update
  fi
  "${KCADM}" "${action}" "${endpoint}" --config "${ADMIN_CONFIG}" -r "${REALM}" \
    -s "name=${MAPPER_NAME}" \
    -s protocol=openid-connect \
    -s protocolMapper=oidc-audience-mapper \
    -s "config.\"included.custom.audience\"=${AGENTGATEWAY_AUDIENCE}" \
    -s 'config."access.token.claim"=true' \
    -s 'config."id.token.claim"=false' \
    -s 'config."introspection.token.claim"=true' >/dev/null 2>&1 || \
    fail "failed to reconcile audience mapper"
}

verify_role() {
  # The shared route role is owned by agentgateway-read-grants.sh (wave 20);
  # a missing role means that hook has not run for this commit, never a
  # reason to create it here. The role's other holders are asserted against
  # the reviewed allowlist THERE, not here: this hook must not fail on
  # agentgateway-mcp holding the same shared role.
  kget "roles/${READ_ROLE_NAME}" --fields id >/dev/null 2>&1 || \
    fail "${READ_ROLE_NAME} is missing; the agentgateway-read-grants hook owns it"
  composite="$(kget "roles/${READ_ROLE_NAME}" --fields composite --format csv --noquotes | nonempty_lines)"
  [ "${composite}" = "false" ] || fail "${READ_ROLE_NAME} must remain non-composite"
}

resolve_service_account() {
  SERVICE_ACCOUNT_ID="$(kget "clients/${CLIENT_UUID}/service-account-user" \
    --fields id --format csv --noquotes | nonempty_lines)"
  SERVICE_ACCOUNT_USERNAME="$(kget "clients/${CLIENT_UUID}/service-account-user" \
    --fields username --format csv --noquotes | nonempty_lines)"
  [ -n "${SERVICE_ACCOUNT_ID}" ] || fail "service account id is empty"
  [ "${SERVICE_ACCOUNT_USERNAME}" = "service-account-${CLIENT_ID}" ] || \
    fail "unexpected service account username"
}

service_account_realm_roles() {
  kget "users/${SERVICE_ACCOUNT_ID}/role-mappings/realm" \
    --fields name --format csv --noquotes | nonempty_lines
}

target_has_direct_role() {
  service_account_realm_roles | grep -Fxq "$1"
}

assert_reviewed_read_roles() {
  # The jarvis identity may hold ONE agentgateway role — the reviewed read
  # route — and nothing else from the agentgateway-read/write families. The
  # umbrella write role, any write domain and any sibling read route all fail
  # closed here (INFRA-477: security approved read-only calendar access;
  # writes would need agentgateway-write and a new review).
  held="$(service_account_realm_roles | grep -E '^agentgateway-(read|write)' || true)"
  for role in ${held}; do
    [ "${role}" = "${READ_ROLE_NAME}" ] || \
      fail "service account holds an unreviewed AgentGateway role: ${role}"
  done
  printf '%s\n' "${held}" | grep -Fxq "${READ_ROLE_NAME}" || \
    fail "service account is missing ${READ_ROLE_NAME}"
}

role_scope_has_direct_role() {
  kget "clients/${CLIENT_UUID}/scope-mappings/realm" \
    --fields name --format csv --noquotes | nonempty_lines | grep -Fxq "$1"
}

ensure_role_scope_mapping() {
  if ! role_scope_has_direct_role "${READ_ROLE_NAME}"; then
    role_id="$(kget "roles/${READ_ROLE_NAME}" --fields id --format csv --noquotes | nonempty_lines)"
    [ -n "${role_id}" ] || fail "${READ_ROLE_NAME} id is empty"
    role_body="$(printf '[{"id":"%s","name":"%s"}]' "${role_id}" "${READ_ROLE_NAME}")"
    "${KCADM}" create "clients/${CLIENT_UUID}/scope-mappings/realm" \
      --config "${ADMIN_CONFIG}" -r "${REALM}" -b "${role_body}" >/dev/null 2>&1 || \
      fail "failed to map ${READ_ROLE_NAME} into the client role scope"
    unset role_body role_id
  fi
  role_scope_has_direct_role "${READ_ROLE_NAME}" || fail "client role scope is missing ${READ_ROLE_NAME}"
  assert_scope_within
}

assert_scope_within() {
  # The client role scope is EXACTLY the reviewed role: an extra mapping
  # widens the matrix the moment the service account is granted that role
  # (SC-100 defect 6 family). Additive reconciliation never removes, so an
  # unexpected entry fails closed before the live flip — nothing is mutated.
  current="$(kget "clients/${CLIENT_UUID}/scope-mappings/realm" \
    --fields name --format csv --noquotes | nonempty_lines)"
  if [ -n "${current}" ]; then
    while IFS= read -r name; do
      [ "${name}" = "${READ_ROLE_NAME}" ] || \
        fail "client role scope has unexpected role ${name}; it widens the reviewed matrix"
    done <<EOF
${current}
EOF
  fi
}

ensure_role_mapping() {
  if ! target_has_direct_role "${READ_ROLE_NAME}"; then
    "${KCADM}" add-roles --config "${ADMIN_CONFIG}" -r "${REALM}" \
      --uid "${SERVICE_ACCOUNT_ID}" --rolename "${READ_ROLE_NAME}" >/dev/null 2>&1 || \
      fail "failed to map ${READ_ROLE_NAME}"
  fi
  target_has_direct_role "${READ_ROLE_NAME}" || fail "direct realm role missing: ${READ_ROLE_NAME}"
  assert_reviewed_read_roles
}

fullscope_value() {
  client_field "${CLIENT_UUID}" fullScopeAllowed
}

client_secret_via_admin() {
  # GET, never POST: reads the current secret without rotating it (same idiom
  # as agentgateway-read-grants.sh). Never printed.
  kget "clients/${CLIENT_UUID}/client-secret" --fields value --format csv --noquotes | nonempty_lines
}

mint_claims() {
  client_secret="$(client_secret_via_admin)"
  [ -n "${client_secret}" ] || fail "client secret is empty for ${CLIENT_ID}"
  "${KCADM}" config credentials \
    --config "${CLIENT_CONFIG}" \
    --server "${KEYCLOAK_URL}" \
    --realm "${REALM}" \
    --client "${CLIENT_ID}" \
    --secret "${client_secret}" >/dev/null 2>&1 || fail "client_credentials token mint failed for ${CLIENT_ID}"
  unset client_secret
  token="$(sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "${CLIENT_CONFIG}" | head -n1)"
  [ -n "${token}" ] || fail "access token is missing"
  payload="$(printf '%s' "${token}" | cut -d. -f2)"
  unset token
  case $((${#payload} % 4)) in
    0) ;;
    2) payload="${payload}==" ;;
    3) payload="${payload}=" ;;
    *) fail "JWT payload has invalid base64url length" ;;
  esac
  claims="$(printf '%s' "${payload}" | tr '_-' '/+' | base64 -d 2>/dev/null)" || fail "JWT decode failed"
  unset payload
  rm -f "${CLIENT_CONFIG}"
  printf '%s' "${claims}"
}

token_realm_roles() {
  # stdin: decoded JWT claims. stdout: sorted comma list of realm_access roles.
  sed -n 's/.*"realm_access"[[:space:]]*:[[:space:]]*{[^}]*"roles"[[:space:]]*:[[:space:]]*\(\[[^]]*\]\).*/\1/p' \
    | tr -d '[]"' | tr ',' '\n' | nonempty_lines | sort | tr '\n' ',' | sed 's/,$//'
}

check_exact_token() {
  # $1 = expected comma list of realm roles. Returns 0 when the minted
  # jarvis-echo token carries exactly those roles with the right azp and the
  # gateway audience, and never an agentgateway-write role. Never calls
  # fail: the post-flip caller must auto-restore fullScopeAllowed before
  # aborting (same discipline as check_mcp_token in the read-grants hook).
  claims="$(mint_claims 2>/dev/null)" || return 1
  printf '%s' "${claims}" | grep -Eq '"azp"[[:space:]]*:[[:space:]]*"'"${CLIENT_ID}"'"' || return 1
  printf '%s' "${claims}" | grep -Fq "${AGENTGATEWAY_AUDIENCE}" || return 1
  if printf '%s' "${claims}" | grep -Eq '"realm_access"[[:space:]]*:[[:space:]]*\{[^}]*"roles"[[:space:]]*:[[:space:]]*\[[^]]*"agentgateway-write'; then
    return 1
  fi
  actual="$(printf '%s' "${claims}" | token_realm_roles)"
  [ -n "${actual}" ] || return 1
  [ "${actual}" = "$1" ] || return 1
  unset claims actual
  return 0
}

verify_exact_token() {
  # Fatal version for the steady state (fullScopeAllowed=false): the reviewed
  # role travels through the client role scope ALONE — the measured realm
  # defaults do not travel (INFRA-44 measurement on
  # openclaw-readonly-agentgateway). EXACT, never a subset.
  claims="$(mint_claims)" || fail "minted ${CLIENT_ID} token could not be obtained"
  printf '%s' "${claims}" | grep -Eq '"azp"[[:space:]]*:[[:space:]]*"'"${CLIENT_ID}"'"' || \
    fail "minted token has wrong azp"
  printf '%s' "${claims}" | grep -Fq "${AGENTGATEWAY_AUDIENCE}" || fail "minted token is missing the gateway audience"
  if printf '%s' "${claims}" | grep -Eq '"realm_access"[[:space:]]*:[[:space:]]*\{[^}]*"roles"[[:space:]]*:[[:space:]]*\[[^]]*"agentgateway-write'; then
    fail "minted token contains a forbidden agentgateway-write role"
  fi
  actual="$(printf '%s' "${claims}" | token_realm_roles)"
  [ -n "${actual}" ] || fail "minted token has no realm_access roles claim"
  [ "${actual}" = "${READ_ROLE_NAME}" ] || \
    fail "minted ${CLIENT_ID} token realm roles are not exactly ${READ_ROLE_NAME}"
  unset claims actual
}

ensure_fullscope_off() {
  # INFRA-45 fail-closed order, scaled to the single role: (a) the role is
  # already mapped into the client role scope and granted; (b) with the flag
  # still true a minted token must carry the reviewed role — this proves the
  # grant is intact before the live step; (c) only then flip; (d) re-verify
  # the exact reviewed role with the flag off. If the post-flip token is
  # off-matrix the flag is restored to true (read-back + confirmation mint)
  # before aborting. In steady state (flag already false) nothing is mutated
  # and an off-matrix token fails closed: it is drift or an attack, not a
  # reason to touch the flag.
  current="$(fullscope_value)"
  flipped=false
  case "${current}" in
    false) ;;
    true)
      claims="$(mint_claims)"
      printf '%s' "${claims}" | grep -Eq '"realm_access"[[:space:]]*:[[:space:]]*\{[^}]*"roles"[[:space:]]*:[[:space:]]*\[[^]]*"'"${READ_ROLE_NAME}"'"' || \
        fail "pre-flip token is missing ${READ_ROLE_NAME}; refusing to flip fullScopeAllowed"
      if printf '%s' "${claims}" | grep -Eq '"realm_access"[[:space:]]*:[[:space:]]*\{[^}]*"roles"[[:space:]]*:[[:space:]]*\[[^]]*"agentgateway-write'; then
        fail "pre-flip token contains a forbidden agentgateway-write role; refusing to flip fullScopeAllowed"
      fi
      unset claims
      "${KCADM}" update "clients/${CLIENT_UUID}" --config "${ADMIN_CONFIG}" -r "${REALM}" \
        -s fullScopeAllowed=false >/dev/null 2>&1 || \
        fail "failed to set fullScopeAllowed=false on ${CLIENT_ID}"
      [ "$(fullscope_value)" = "false" ] || \
        fail "fullScopeAllowed did not become false on ${CLIENT_ID}"
      flipped=true
      ;;
    *) fail "unexpected fullScopeAllowed value for ${CLIENT_ID}" ;;
  esac
  if check_exact_token "${READ_ROLE_NAME}"; then
    return 0
  fi
  if [ "${flipped}" = "true" ]; then
    "${KCADM}" update "clients/${CLIENT_UUID}" --config "${ADMIN_CONFIG}" -r "${REALM}" \
      -s fullScopeAllowed=true >/dev/null 2>&1 || \
      fail "post-flip token is off-matrix AND fullScopeAllowed could not be restored on ${CLIENT_ID}: manual intervention required"
    [ "$(fullscope_value)" = "true" ] || \
      fail "fullScopeAllowed did not become true on ${CLIENT_ID} during auto-restore: manual intervention required"
    claims="$(mint_claims)"
    printf '%s' "${claims}" | grep -Eq '"realm_access"[[:space:]]*:[[:space:]]*\{[^}]*"roles"[[:space:]]*:[[:space:]]*\[[^]]*"'"${READ_ROLE_NAME}"'"' || \
      fail "restored token does not carry ${READ_ROLE_NAME} on ${CLIENT_ID}: manual intervention required"
    unset claims
    fail "minted ${CLIENT_ID} token after fullScopeAllowed=false is not exactly ${READ_ROLE_NAME}; fullScopeAllowed was restored to true and confirmed — aborting"
  fi
  fail "minted ${CLIENT_ID} token with fullScopeAllowed=false is not exactly ${READ_ROLE_NAME} (flag unchanged by this run)"
}

verify_client() {
  CLIENT_UUID="$(require_client)"
  assert_client_boolean "${CLIENT_UUID}" enabled true
  assert_client_boolean "${CLIENT_UUID}" publicClient false
  assert_client_boolean "${CLIENT_UUID}" standardFlowEnabled false
  assert_client_boolean "${CLIENT_UUID}" directAccessGrantsEnabled false
  assert_client_boolean "${CLIENT_UUID}" serviceAccountsEnabled true
  assert_client_boolean "${CLIENT_UUID}" fullScopeAllowed false
  [ -n "$(mapper_uuid_optional "${MAPPER_NAME}")" ] || fail "audience mapper missing"
  role_scope_has_direct_role "${READ_ROLE_NAME}" || fail "client role scope is missing ${READ_ROLE_NAME}"
  assert_scope_within
  resolve_service_account
  target_has_direct_role "${READ_ROLE_NAME}" || fail "direct realm role missing: ${READ_ROLE_NAME}"
  assert_reviewed_read_roles
}

rollback_identity() {
  # Deleting the client removes its service account and with it the reviewed
  # grant. The role itself is retained: it is owned by
  # agentgateway-read-grants.sh and referenced by the gateway CEL, and it
  # keeps its other reviewed holders (agentgateway-mcp) — asserting
  # emptiness there would fail by design.
  uuid="$(resolve_client_optional)"
  if [ -n "${uuid}" ]; then
    "${KCADM}" delete "clients/${uuid}" --config "${ADMIN_CONFIG}" -r "${REALM}" >/dev/null 2>&1 || \
      fail "failed to delete ${CLIENT_ID}"
  fi
  [ -z "$(resolve_client_optional)" ] || fail "client ${CLIENT_ID} remains after rollback"
  printf '{"client_id":"%s","realm_role":"%s","client_present":false,"role_retained":true}\n' \
    "${CLIENT_ID}" "${READ_ROLE_NAME}"
}

login_admin
progress authenticated
case "${MODE}" in
  ensure)
    verify_role
    upsert_client
    progress client-reconciled
    upsert_audience_mapper
    ensure_role_scope_mapping
    progress role-scope-verified
    resolve_service_account
    ensure_role_mapping
    progress role-mapping-verified
    ensure_fullscope_off
    verify_client
    progress token-verified
    printf '{"client_id":"%s","realm_role":"%s","present":true,"fullscope_allowed":false,"token_verified":true}\n' \
      "${CLIENT_ID}" "${READ_ROLE_NAME}"
    ;;
  audit)
    verify_role
    verify_client
    verify_exact_token
    printf '{"client_id":"%s","realm_role":"%s","present":true,"fullscope_allowed":false,"token_verified":true}\n' \
      "${CLIENT_ID}" "${READ_ROLE_NAME}"
    ;;
  rollback)
    rollback_identity
    ;;
esac
