apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - cronjob.yaml
configMapGenerator:
  - name: onepassword-change-detector
    namespace: external-secrets-operator
    files:
      - detect.py
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: onepassword-change-detector
