---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  edani-public-lan.server: |
    e-dani.com:53 {
      errors
      hosts {
        100.83.56.98 dgx.e-dani.com
        100.83.56.98 s3.e-dani.com
        ttl 60
        fallthrough
      }
      forward . /etc/resolv.conf
      cache 30
    }
